name: Continious Integration
on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: vendor
        key: dependencies-${{ matrix.php-versions }}-${{ hashFiles('composer.json') }}
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov
    - name: Install dependencies
      run: composer install -n --prefer-dist
      if: matrix.php-versions != '8.0'
    - name: Install dependencies
      run: composer self-update --snapshot && composer install -n --prefer-dist --ignore-platform-req=php
      if: matrix.php-versions == '8.0'
    - name: Run PHPUnit unit tests
      run: vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --whitelist src/
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.php-versions == '7.4'

  infection:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: vendor
        key: dependencies-${{ matrix.php-versions }}-${{ hashFiles('composer.json') }}
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov
    - name: Install dependencies
      run: composer install -n --prefer-dist
      if: matrix.php-versions != '8.0'
    - name: Install dependencies
      run: composer self-update --snapshot && composer install -n --prefer-dist --ignore-platform-req=php
      if: matrix.php-versions == '8.0'
    - name: Run mutation tests
      run: vendor/bin/infection --show-mutations --debug -vvv

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      env:
        REQUIRE_DEV: true
      with:
        args: analyse
