name: Continious Integration
on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3']
    steps:
    - uses: actions/checkout@v1
    - uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov
    - name: Install dependencies
      run: composer install -n --prefer-dist
    - name: Run PHPUnit unit tests
      run: vendor/bin/phpunit tests/ --coverage-xml=coverage.xml --whitelist src/ --coverage-text
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse
