name: Continious Integration
on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3']
    container:
      image: php:${{ matrix.php-versions }}-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - name: Install dependencies
      run: composer install -n --prefer-dist
    - name: Install pcov to generate code coverage
      run: pecl install pcov
    - name: Run PHPUnit unit tests
      run: php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" vendor/bin/phpunit tests/ --coverage-xml=coverage.xml

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse
