name: Continious Integration
on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3']
    container:
      image: php:${{ matrix.php-versions }}-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - name: Install dependencies
      run: composer install -n --prefer-dist
    - name: Run PHPUnit unit tests
      run: vendor/bin/phpunit tests/
